### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by loopier** [veryprofessionaldodo/Krita-Photobash-Images-Plugin#2]
Hi,

I installed the plugin last night and worked fine.  But this morning it prevents Krita from starting.
If I set `enable_photobash_images=false` in my `.config/kritarc` file, it runs fine.

I'm  on Arch Linux (Linux 5.15.11-arch2-1 x86_64) running Krita 5.0.0.

Here's the error log:

```
TypeError
Python 3.10.1: /usr/bin/python3
Mon Dec 27 11:07:09 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/lib/krita-python-libs/krita/dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'photobash_images.photobash.PhotobashDocker'>

 /usr/share/krita/pykrita/photobash_images/photobash.py in __init__(self=<photobash_images.photobash.PhotobashDocker object>)
   38         self.currImageScale = 100
   39 
   40         self.setLayout()
   41 
   42 
self = <photobash_images.photobash.PhotobashDocker object>
self.setLayout = <bound method PhotobashDocker.setLayout of <photobash_images.photobash.PhotobashDocker object>>

 /usr/share/krita/pykrita/photobash_images/photobash.py in setLayout(self=<photobash_images.photobash.PhotobashDocker object>)
   75                 button.setMaximumHeight(3000)
   76                 button.setMaximumWidth(3000)
   77                 button.setMinimumHeight(self.mainWidget.height() / 3)
   78                 button.setMinimumWidth(self.mainWidget.width() / 3)
   79 
button = <PyQt5.QtWidgets.QToolButton object>
button.setMinimumHeight = <built-in method setMinimumHeight of QToolButton object>
self = <photobash_images.photobash.PhotobashDocker object>
self.mainWidget = <PyQt5.QtWidgets.QWidget object>
self.mainWidget.height = <built-in method height of QWidget object>
TypeError: setMinimumHeight(self, int): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("setMinimumHeight(self, int): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/lib/krita-python-libs/krita/dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "/usr/share/krita/pykrita/photobash_images/photobash.py", line 40, in __init__
    self.setLayout()
  File "/usr/share/krita/pykrita/photobash_images/photobash.py", line 77, in setLayout
    button.setMinimumHeight(self.mainWidget.height() / 3)
TypeError: setMinimumHeight(self, int): argument 1 has unexpected type 'float'

```

**Comment by veryprofessionaldodo** [comment]
Thank you for the logs! That makes our job a lot easier. I'll look it up in the next weeks, thank you again!
