### ISSUE TITLE
Addon not working in Krita 5.2.+

### ISSUE THREAD

**Issue by MeshVoid** [veryprofessionaldodo/Krita-Photobash-Images-Plugin#5]
Hi! I'm having problems running photobash plugin in 5.2.0 and 5.2.1 versions of Krita. It loads fine, but it shows an errot whenever I choose an image from the docker view. 
Here's an error log I get after clicking on an image thumbnail in photobask docker to import it:

TypeError
Python 3.10.7: C:\Apps\Krita\bin\krita.exe
Fri Nov 24 15:31:06 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Apps\Krita\share\krita\pykrita\photobash_images\photobash_images_docker.py in buttonClick(self=<photobash_images.photobash_images_docker.PhotobashDocker object>, position=0)
  448     def buttonClick(self, position):
  449         if position < len(self.foundImages) - len(self.imagesButtons) * self.currPage:
  450             self.addImageLayer(self.foundImages[position + len(self.imagesButtons) * self.currPage])
  451 
  452     def changePath(self):
self = <photobash_images.photobash_images_docker.PhotobashDocker object>
self.addImageLayer = <bound method PhotobashDocker.addImageLayer of <....photobash_images_docker.PhotobashDocker object>>
self.foundImages = ['C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments1.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...-apartments-shopfronts-shutters/apartments2-2.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments2.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...artments-shopfronts-shutters/apartments2_side.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments4.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments5.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments6.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments7.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments8.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments9.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...artments-shopfronts-shutters/apartment_block5.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...artments-shopfronts-shutters/apartment_block6.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...artments-shopfronts-shutters/apartment_block7.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...artments-shopfronts-shutters/apartment_block8.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/building_5c.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...partments-shopfronts-shutters/building_center.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...nts-shopfronts-shutters/building_church_side1.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...pfronts-shutters/building_church_side_bottom1.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...pfronts-shutters/building_church_side_bottom2.png', 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...-shopfronts-shutters/building_church_side_top.png', ...]
position = 0
builtinlen = <built-in function len>
self.imagesButtons = [<photobash_images.photobash_images_modulo.Photobash_Button object>, <photobash_images.photobash_images_modulo.Photobash_Button object>, <photobash_images.photobash_images_modulo.Photobash_Button object>, <photobash_images.photobash_images_modulo.Photobash_Button object>, <photobash_images.photobash_images_modulo.Photobash_Button object>, <photobash_images.photobash_images_modulo.Photobash_Button object>, <photobash_images.photobash_images_modulo.Photobash_Button object>, <photobash_images.photobash_images_modulo.Photobash_Button object>, <photobash_images.photobash_images_modulo.Photobash_Button object>]
self.currPage = 0

 C:\Apps\Krita\share\krita\pykrita\photobash_images\photobash_images_docker.py in addImageLayer(self=<photobash_images.photobash_images_docker.PhotobashDocker object>, photoPath='C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments1.png')
  345         # Scale Image
  346         if self.fitCanvasChecked:
  347             image = QImage(photoPath).scaled(doc.width() * scale, doc.height() * scale, Qt.KeepAspectRatio, Qt.SmoothTransformation)
  348         else:
  349             image = QImage(photoPath)
image undefined
global QImage = <class 'PyQt5.QtGui.QImage'>
photoPath = 'C:/Sketchbook/000_FOR_PHOTOBASH/000_BUILDINGS/bu...gs-apartments-shopfronts-shutters/apartments1.png'
).scaled undefined
doc = <PyKrita.krita.Document object>
doc.width = <built-in method width of Document object>
scale = 1.0
doc.height = <built-in method height of Document object>
global Qt = <class 'PyQt5.QtCore.Qt'>
Qt.KeepAspectRatio = 1
Qt.SmoothTransformation = 1
TypeError: arguments did not match any overloaded call:
  scaled(self, int, int, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
  scaled(self, QSize, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
    __cause__ = None
    __class__ = <class 'TypeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of TypeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of TypeError object>
    __doc__ = 'Inappropriate argument type.'
    __eq__ = <method-wrapper '__eq__' of TypeError object>
    __format__ = <built-in method __format__ of TypeError object>
    __ge__ = <method-wrapper '__ge__' of TypeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
    __gt__ = <method-wrapper '__gt__' of TypeError object>
    __hash__ = <method-wrapper '__hash__' of TypeError object>
    __init__ = <method-wrapper '__init__' of TypeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of TypeError object>
    __lt__ = <method-wrapper '__lt__' of TypeError object>
    __ne__ = <method-wrapper '__ne__' of TypeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of TypeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
    __repr__ = <method-wrapper '__repr__' of TypeError object>
    __setattr__ = <method-wrapper '__setattr__' of TypeError object>
    __setstate__ = <built-in method __setstate__ of TypeError object>
    __sizeof__ = <built-in method __sizeof__ of TypeError object>
    __str__ = <method-wrapper '__str__' of TypeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("arguments did not match any overloaded call:\n  s...ormation): argument 1 has unexpected type 'float'",)
    with_traceback = <built-in method with_traceback of TypeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Apps\Krita\share\krita\pykrita\photobash_images\photobash_images_docker.py", line 450, in buttonClick
    self.addImageLayer(self.foundImages[position + len(self.imagesButtons) * self.currPage])
  File "C:\Apps\Krita\share\krita\pykrita\photobash_images\photobash_images_docker.py", line 347, in addImageLayer
    image = QImage(photoPath).scaled(doc.width() * scale, doc.height() * scale, Qt.KeepAspectRatio, Qt.SmoothTransformation)
TypeError: arguments did not match any overloaded call:
  scaled(self, int, int, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'
  scaled(self, QSize, aspectRatioMode: Qt.AspectRatioMode = Qt.IgnoreAspectRatio, transformMode: Qt.TransformationMode = Qt.FastTransformation): argument 1 has unexpected type 'float'

**Comment by duskydd** [comment]
I implemented a simple fix with #6 working on Krita 5.2.1

**Comment by veryprofessionaldodo** [comment]
Apologies, I haven't seen this code so long I kind of abandoned this. @duskydd thank you so much for the fix, working on it now!
